import { useRouter } from "next/router";
import Layout from "../../components/Layout.js";
import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import { useState } from "react";
import Head from "next/head";

export default function CreateArticles() {
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const router = useRouter();
  const user = useUser();
  const initialState = {
    title: "",
    slug: "",
    message: "",
  };
  const [articleData, setArticleData] = useState(initialState);

  const handleChange = (e) => {
    setArticleData({ ...articleData, [e.target.name]: e.target.value });
  };

  const createArticle = async () => {
    const { data, error } = await supabase
      .from("articles")
      .insert([
        {
          title: articleData.title,
          slug: articleData.slug,
          message: articleData.message,
          user_email: user?.email.toLowerCase(),
          user_id: user?.id,
        },
      ])
      .single();
    if (error) {
      setMessage("Sorry, an unexpected error occured. Be sure to be login !");
    } else {
      setArticleData(initialState);
      router.push("/articles");
      setMessage(
        <div>
          <h2 className="text-center mt-3">Confirmation</h2>
          <p>Thank you for adding an article.</p>
        </div>
      );
    }
  };

  return (
    <Layout>
      <Head>
        <title>WebTech - Create Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className="[&_span]:block grid gap-3">
        <div>
          <label>
            <span>Title</span>
            <input
              type="text"
              name="title"
              onChange={handleChange}
              className="dark:text-black"
            />
          </label>
        </div>
        <div>
          <label>
            <span>Slug</span>
            <input
              type="text"
              name="slug"
              onChange={handleChange}
              className="dark:text-black"
            />
          </label>
        </div>
        <div>
          <label>
            <span>Message</span>
            <textarea
              name="message"
              onChange={handleChange}
              className="dark:text-black"
            />
          </label>
        </div>
        <div>
          <label>
            <span>{user?.email}</span>
          </label>
        </div>
        <div>
          <button
            className="rounded py-1 px-3 text-white bg-slate-500 hover:bg-blue-500"
            onClick={createArticle}
          >
            Create Article
          </button>
        </div>
      </form>
      {message && (
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      )}
    </Layout>
  );
}
