import { useState } from "react";
import Head from "next/head";
import Layout from "../components/Layout.js";

export default function LoginNative() {
  const [count, setCount] = useState(0);
  const onIncrement = function (e) {
    setCount(++count);
  };
  return (
    <Layout>
      <Head>
        <title>WebTech - login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="wt-title">Use state</h1>
        <div>{count}</div>
        <div>
          <button
            className="bg-slate-500 hover:bg-blue-500 text-white px-3 py-2 rounded"
            onClick={onIncrement}
          >
            Click me
          </button>
        </div>
      </div>
    </Layout>
  );
}
